/**
 * CatalogStore — read-side abstraction over catalog data.
 *
 * Purpose: let tools look up folder/article metadata without caring where the
 * data physically lives. Today the data is INDEX.md markdown files under
 * `.open-knowledge/catalogs/<path>/INDEX.md`; tomorrow it may be SQLite rows
 * or a different format. Tools depend on this interface, not on the storage.
 *
 * Scope note: this is **read-side only**. Generation of catalog files is still
 * owned by `packages/cli/src/content/mirror-catalog.ts` — that's the write
 * path and it stays unchanged in this spec (D3). When a new backend ships,
 * both sides move together.
 */
import { existsSync } from 'node:fs';
import { readFile } from 'node:fs/promises';
import { dirname, join, relative, resolve } from 'node:path';
import { z } from 'zod';
import { CATALOG_FILENAME, OK_DIR } from '../constants.ts';
import { parseFrontmatter } from '../utils/frontmatter.ts';

// ── Types ───────────────────────────────────────────────────────────────

export interface ArticleMeta {
  title: string;
  description: string;
  tags: string[];
}

export interface ArticleEntry extends ArticleMeta {
  /** Path relative to project root. */
  path: string;
}

export interface SubfolderEntry {
  name: string;
  title: string;
  description: string;
  articleCount: number;
}

export interface CatalogData {
  title: string;
  description: string;
  articles: ArticleEntry[];
  subfolders: SubfolderEntry[];
}

export interface CatalogStore {
  /**
   * Read the catalog for a given directory (relative to project root).
   * Returns null when no catalog exists for that directory.
   */
  getCatalog(relDir: string): Promise<CatalogData | null>;

  /**
   * Read the metadata (frontmatter) for an article.
   * Reads directly from the source file's frontmatter — not from catalog data —
   * since per-article descriptions live inline.
   */
  getArticleMeta(relPath: string): Promise<ArticleMeta | null>;
}

// ── Schemas for frontmatter parsing ─────────────────────────────────────

const IndexFrontmatterSchema = z.object({
  title: z.string().optional(),
  description: z.string().optional(),
});

const ArticleFrontmatterSchema = z.object({
  title: z.string().optional(),
  description: z.string().optional(),
  tags: z.array(z.string()).default([]),
});

// ── INDEX.md parsing ────────────────────────────────────────────────────

/** Matches: - **[Title](path)** — description Tags: a, b */
const ARTICLE_LINE_RE = /^- \*\*\[([^\]]+)\]\(([^)]+)\)\*\*(?: — (.+?))?(?: Tags: (.+))?$/;

/** Matches: - **[Title](path)** (N article(s)) — description */
const SUBFOLDER_LINE_RE = /^- \*\*\[([^\]]+)\]\(([^)]+)\)\*\* \((\d+) articles?\)(?: — (.+))?$/;

interface ParsedCatalog {
  title: string;
  description: string;
  articles: ArticleEntry[];
  subfolders: SubfolderEntry[];
}

function parseCatalogMarkdown(content: string): ParsedCatalog {
  const fm = parseFrontmatter(content, IndexFrontmatterSchema);
  const title = fm?.title ?? '';
  const description = fm?.description ?? '';

  const articles: ArticleEntry[] = [];
  const subfolders: SubfolderEntry[] = [];

  // Strip frontmatter so section headers + list items are cleanly addressable
  const body = content.replace(/^---\r?\n[\s\S]*?\r?\n---(?:\r?\n|$)/, '');

  let section: 'articles' | 'subfolders' | null = null;
  for (const rawLine of body.split('\n')) {
    const line = rawLine.trimEnd();
    if (line === '## Articles') {
      section = 'articles';
      continue;
    }
    if (line === '## Subfolders') {
      section = 'subfolders';
      continue;
    }
    if (line.startsWith('## ')) {
      section = null;
      continue;
    }

    if (section === 'articles') {
      const m = line.match(ARTICLE_LINE_RE);
      if (m) {
        const [, articleTitle, articlePath, desc, tags] = m;
        articles.push({
          title: articleTitle ?? '',
          description: desc?.trim() ?? '',
          tags: tags
            ? tags
                .split(',')
                .map((t) => t.trim())
                .filter(Boolean)
            : [],
          path: articlePath ?? '',
        });
      }
    } else if (section === 'subfolders') {
      const m = line.match(SUBFOLDER_LINE_RE);
      if (m) {
        const [, sfTitle, , countStr, desc] = m;
        subfolders.push({
          name: sfTitle ?? '',
          title: sfTitle ?? '',
          description: desc?.trim() ?? '',
          articleCount: Number.parseInt(countStr ?? '0', 10),
        });
      }
    }
  }

  return { title, description, articles, subfolders };
}

// ── IndexMd implementation ──────────────────────────────────────────────

export interface IndexMdCatalogStoreOptions {
  /** Absolute path to the project root. */
  projectDir: string;
}

/**
 * Default CatalogStore implementation — reads INDEX.md files under
 * `.open-knowledge/catalogs/` that are generated by mirror-catalog.
 */
export class IndexMdCatalogStore implements CatalogStore {
  private readonly projectDir: string;
  private readonly catalogsDir: string;

  constructor(opts: IndexMdCatalogStoreOptions) {
    this.projectDir = resolve(opts.projectDir);
    this.catalogsDir = join(this.projectDir, OK_DIR, 'catalogs');
  }

  async getCatalog(relDir: string): Promise<CatalogData | null> {
    const normalized = relDir === '' || relDir === '.' ? '' : relDir;
    const indexPath = join(this.catalogsDir, normalized, CATALOG_FILENAME);
    if (!existsSync(indexPath)) return null;
    const content = await readFile(indexPath, 'utf-8');
    const parsed = parseCatalogMarkdown(content);
    return {
      title: parsed.title || (normalized ? (normalized.split('/').pop() ?? '') : 'Project Content'),
      description: parsed.description,
      articles: parsed.articles,
      subfolders: parsed.subfolders,
    };
  }

  async getArticleMeta(relPath: string): Promise<ArticleMeta | null> {
    const abs = resolve(this.projectDir, relPath);
    // Guard: stay within project root
    if (!abs.startsWith(`${this.projectDir}/`) && abs !== this.projectDir) {
      return null;
    }
    if (!existsSync(abs)) return null;
    const content = await readFile(abs, 'utf-8');
    const fm = parseFrontmatter(content, ArticleFrontmatterSchema);
    if (!fm) {
      // File has no frontmatter — derive title from filename
      const basename = relPath.split('/').pop() ?? relPath;
      const nameWithoutExt = basename.replace(/\.md$/, '');
      return { title: nameWithoutExt, description: '', tags: [] };
    }
    return {
      title: fm.title ?? relPath.split('/').pop()?.replace(/\.md$/, '') ?? '',
      description: fm.description ?? '',
      tags: fm.tags,
    };
  }
}

// ── Helpers for consumers ───────────────────────────────────────────────

/**
 * Resolve the parent directory of a project-relative path, returning it in
 * project-relative form (`''` for root). Used by `read_document` to look up
 * the folder-level catalog entry for a given article.
 */
export function parentDirOf(relPath: string): string {
  const dir = dirname(relPath);
  return dir === '.' ? '' : dir;
}

/**
 * Ensure a path is inside the project root. Returns the path relative to
 * the project root. Throws when the path escapes the project.
 */
export function toProjectRelative(projectDir: string, input: string): string {
  const abs = resolve(projectDir, input);
  const rel = relative(projectDir, abs);
  if (rel.startsWith('..') || rel.startsWith('/')) {
    throw new Error(`Path outside project root: ${input}`);
  }
  return rel;
}
