/**
 * Registry types — React-free metadata for JSX component descriptors.
 *
 * Core owns the typed metadata; the app layer adds `Component: React.ComponentType<any>`.
 * This file MUST NOT import React.
 */

// ── PropDef discriminated union ──────────────────────────────────────────────

export interface PropDefBase {
  name: string;
  required: boolean;
  description?: string;
  /**
   * Suppresses the prop from the auto-generated PropPanel UI, while keeping
   * it in the descriptor for documentation and MCP queries. Useful for extracted
   * props that shouldn't surface to authors (className, ref, style, internal-only
   * fields). Analogous to Storybook's `argTypes.X.control: false`. The
   * build-registry JSDoc extractor populates this from an `@hidden` tag on the
   * source prop.
   */
  hidden?: boolean;
}

export interface PropDefString extends PropDefBase {
  type: 'string';
  defaultValue?: string;
}

export interface PropDefBoolean extends PropDefBase {
  type: 'boolean';
  defaultValue?: boolean;
}

export interface PropDefNumber extends PropDefBase {
  type: 'number';
  defaultValue?: number;
}

export interface PropDefEnum extends PropDefBase {
  type: 'enum';
  enumValues: [string, ...string[]];
  defaultValue?: string;
}

export interface PropDefReactNode extends PropDefBase {
  type: 'reactnode';
}

export type PropDef =
  | PropDefString
  | PropDefBoolean
  | PropDefNumber
  | PropDefEnum
  | PropDefReactNode;

// ── JsxComponentMeta ─────────────────────────────────────────────────────────

/**
 * React-free component metadata for the descriptor registry.
 *
 * NG14: registry tracks block components only. No isInline field —
 * inline JSX is the thin jsxInline node and doesn't use descriptors.
 */
export interface JsxComponentMeta {
  /** Component tag name, or '*' for the wildcard fallback. */
  name: string;
  /** PropPanel/slash-menu hint; NodeViewContent always renders per Precedent #26. */
  hasChildren: boolean;
  /** Hint: component is typically self-closing (e.g., <Chart />). */
  isSelfClosing?: boolean;
  /** Auto-generated by react-docgen-typescript or hand-authored. */
  props: PropDef[];
  /** Slash menu icon name (resolved to Lucide in app). */
  icon?: string;
  /** Slash menu grouping category. */
  category?: 'content' | 'layout' | 'media' | 'data';
  /** Slash menu label. */
  displayName?: string;
  /** One-line summary for slash menu + MCP agent discovery. */
  description?: string;
  /** Slash-command aliases (e.g., Callout → ['note','warning','tip','info','alert']). */
  searchTerms?: string[];
  /** For empty-container placeholder UX — Steps → 'Step', Tabs → 'Tab'. */
  emptyChildName?: string;
}
