import { readFileSync } from 'node:fs';
import { formatHex, parse as parseColor } from 'culori';

export interface ChromeTokens {
  light: string;
  dark: string;
}

const SIDEBAR_DECL_RE = /--sidebar:\s*([^;]+);/;

function findBlockBodies(css: string, selector: string): string[] {
  const selectorRe = new RegExp(
    `(^|\\n)\\s*${selector.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\s*\\{`,
    'g',
  );
  const bodies: string[] = [];
  let match: RegExpExecArray | null = selectorRe.exec(css);
  while (match !== null) {
    const braceOpen = match.index + match[0].length - 1;
    let depth = 1;
    let cursor = braceOpen + 1;
    while (cursor < css.length && depth > 0) {
      const ch = css[cursor];
      if (ch === '{') depth += 1;
      else if (ch === '}') depth -= 1;
      if (depth === 0) {
        bodies.push(css.slice(braceOpen + 1, cursor));
        break;
      }
      cursor += 1;
    }
    if (depth !== 0) {
      throw new Error(`chrome-resolver: unbalanced braces while scanning ${selector}`);
    }
    match = selectorRe.exec(css);
  }
  return bodies;
}

function extractSidebarValue(css: string, selector: string): string {
  const bodies = findBlockBodies(css, selector);
  for (const body of bodies) {
    const decl = body.match(SIDEBAR_DECL_RE);
    if (decl && decl[1] !== undefined) {
      return decl[1].trim();
    }
  }
  throw new Error(`chrome-resolver: --sidebar declaration not found in any ${selector} block`);
}

function resolveToHex(cssColor: string, label: string): string {
  const parsed = parseColor(cssColor);
  if (parsed === undefined) {
    throw new Error(`chrome-resolver: culori failed to parse ${label} value: ${cssColor}`);
  }
  const hex = formatHex(parsed);
  if (hex === undefined) {
    throw new Error(`chrome-resolver: culori failed to convert ${label} to sRGB hex: ${cssColor}`);
  }
  return hex;
}

export function resolveChromeTokensFromCss(cssPath: string): ChromeTokens {
  const css = readFileSync(cssPath, 'utf8');
  const lightValue = extractSidebarValue(css, ':root');
  const darkValue = extractSidebarValue(css, '.dark');
  return {
    light: resolveToHex(lightValue, 'light'),
    dark: resolveToHex(darkValue, 'dark'),
  };
}

export function renderChromeConstantsModule(tokens: ChromeTokens): string {
  return `/**
 * Chrome background sRGB hex constants. Regenerated by
 * \`packages/core/scripts/generate-chrome-tokens.ts\` from the
 * \`--sidebar\` Tailwind token in \`packages/app/src/globals.css\`. Drift
 * between this file and the CSS is caught by \`chrome.test.ts\`.
 *
 * Consumers:
 *   - \`packages/app/index.html\` inline <style> (Vite plugin substitutes
 *     placeholders at build time)
 *   - \`packages/desktop/src/main/index.ts\` BrowserWindow chrome
 *
 * Do NOT hand-edit. Run \`bun run packages/core/scripts/generate-chrome-tokens.ts\`
 * after changing \`--sidebar\` in globals.css.
 */
export const CHROME_BG_LIGHT = '${tokens.light}' as const;
export const CHROME_BG_DARK = '${tokens.dark}' as const;
`;
}
